// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2v_ENNn0Rywmq-GwIeZb57-Mgh-7OSXA',
    appId: '1:546491980143:web:7d3fe9458c2ccde0ccb09a',
    messagingSenderId: '546491980143',
    projectId: 'translation-call-2d597',
    authDomain: 'translation-call-2d597.firebaseapp.com',
    storageBucket: 'translation-call-2d597.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsfUuKFe178gJWTbq4FYHn-mO77Zm3a0',
    appId: '1:82302466532:android:db1910d561ecb0108a6ff1',
    messagingSenderId: '82302466532',
    projectId: 'translation-4a3fc',
    storageBucket: 'translation-4a3fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-84n41AW5kwtq9tKWOIkI0zWKS745ZY',
    appId: '1:82302466532:ios:bf57e895d9999ded8a6ff1',
    messagingSenderId: '82302466532',
    projectId: 'translation-4a3fc',
    storageBucket: 'translation-4a3fc.firebasestorage.app',
    iosBundleId: 'com.example.translation',
  );

}